### ISSUE TITLE
Question: Is DOM Batching implemented in worker-dom

### ISSUE THREAD

**Issue by writepubapp** [ampproject/worker-dom#163]
Hello - 

[FastDom ](https://github.com/wilsonpage/fastdom) - another DOM project with origins inside Google, states the following regarding it's value proposition: 

> FastDom works as a regulatory layer between your app/library and the DOM. By batching DOM access we avoid unnecessary document reflows and dramatically speed up layout performance. Each measure/mutate job is added to a corresponding measure/mutate queue. The queues are emptied (reads, then writes) at the turn of the next frame using `window.requestAnimationFrame`.

Does worker-dom implement similar batching for actual DOM operations in the main thread (proxied from the worker). If not, would you please consider adding this, possibly even using FastDom. 

Adding batching should theoretically not affect any API that worker-dom currently offers. Also, for the most part, batching would eliminate the need to include a virtual-dom implementation, and further benefit, performance wise,  from decades of optimizations that browsers have implemented in handling batching.

Thanks

**Comment by kristoferbaxter** [comment]
>Does worker-dom implement similar batching for actual DOM operations in the main thread (proxied from the worker). If not, would you please consider adding this, possibly even using FastDom.

DOM writes are batched within `requestAnimationFrame` ticks. (https://github.com/ampproject/worker-dom/blob/master/src/main-thread/mutator.ts#L128)

We haven't implemented Layout reads yet, but our plan is to implement async variants of the known methods (and a Babel transform for author code running in the Worker environment). Since these will return a promise, they should be naturally batched in the same manner as DOM writes.

**Comment by writepubapp** [comment]
Thank you for the explanation. Closing this.
