### ISSUE TITLE
Comparison with other DOM implementations

### ISSUE THREAD

**Issue by niutech** [ampproject/worker-dom#22]
How does WorkerDOM compare with other DOM implementations which can run in a Web Worker?
 - [JSDOM](https://github.com/jsdom/jsdom)
 - [XMLDOM](https://github.com/jindw/xmldom)
 - [Domino](https://github.com/fgnass/domino)
 - [Via.js](https://github.com/AshleyScirra/via.js)

or with Virtual DOM implementations:
 - [React Worker DOM](https://github.com/web-perf/react-worker-dom)
 - [Preact Worker Demo](https://github.com/developit/preact-worker-demo)

This should be described in the README.

**Comment by kristoferbaxter** [comment]
Likely will not do a comparison with other projects, but instead explain the goals of WorkerDOM a bit further. 

**Short version**: Intended to run primarily in a worker, attached to a real main thread DOM. Additionally, makes a specific set of tradeoffs to ensure it remains small and compliant with the APIs that frameworks require instead of being a feature complete representation of the DOM.

If other implementations end up solving the problems this library is attempting to resolve, but in a superior way... then this project will just leverage another DOM solution.

**Comment by niutech** [comment]
Thanks! But what are the problems WorkerDOM is trying to resolve,
which are not being already resolved by other DOM implementations
running in a Web Worker? What are the criteria?

**Comment by kristoferbaxter** [comment]
WorkerDOM is Intended to run primarily in a worker, attached to a real main thread DOM. 

It can make several assumptions and extensions to DOM APIs as a result:
1. Async versions of sync methods like `getBoundingClientRect`.
2. Borrow the keys for `CSSStyleDeclaration` from the main thread during Worker creation.
3. In the future ship different DOM implementations specific to the framework used in worker code.

It's specific set of tradeoffs hopefully ensure it remains small and compliant with the APIs that frameworks require instead of being a feature complete representation of the DOM. We're attempting to keep WorkerDOM's implementation quite small to reduce its impact on page load performance.
