### ISSUE TITLE
Multiple amp-script elements causes exception

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#297]
```html
<amp-script layout=container src="/simple.js"><button id="hello">hello</button></amp-script>

<!-- Removing this prevents the error -->
<amp-script layout=container src="/empty.js"><button>hello</button></amp-script>
```

In `simple.js`:
```js
document.getElementById('hello').addEventListener('click', () => {});
```

On load, the following line throws a `Cannot read property 'onchange' of undefined` exception:

https://github.com/ampproject/worker-dom/blob/ec1decd8961372e0a571c2a3b1f2ee40d9f1587d/src/main-thread/commands/event-subscription.ts#L107

**Comment by dvoytenko** [comment]
This is due to the fact that some data structures in https://github.com/ampproject/worker-dom/blob/master/src/main-thread/nodes.ts#L21 and elsewhere are module-scoped (e.g. `let NODES: Map<number, Node>` and `let BASE_ELEMENT: HTMLElement`). Runtime-wise they workout to be globally-scoped. Thus they are being overwritten by different instances of `amp-experiment` and thus there are many race conditions and other types of conflicts.
